package net.bramp.ffmpeg;

import net.bramp.ffmpeg.info.Codec;

/**
 * Class that contains all Codecs as defined in the unit tests
 * This should not be used to test if a codec is available, because every
 * install of ffmpeg is different. Call ffmpeg.codec() to discover.
 * @author bramp
 *
 */
public class Codecs {

	public static Codec[] CODECS = new Codec[] {
		new Codec("4xm",              "4X Movie"),
		new Codec("8bps",             "QuickTime 8BPS video"),
		new Codec("8svx_exp",         "8SVX exponential"),
		new Codec("8svx_fib",         "8SVX fibonacci"),
		new Codec("a64multi",         "Multicolor charset for Commodore 64"),
		new Codec("a64multi5",        "Multicolor charset for Commodore 64, extended with 5th color (colram)"),
		new Codec("aac",              "Advanced Audio Coding"),
		new Codec("aac_latm",         "AAC LATM (Advanced Audio Codec LATM syntax)"),
		new Codec("aasc",             "Autodesk RLE"),
		new Codec("ac3",              "ATSC A/52A (AC-3)"),
		new Codec("ac3_fixed",        "ATSC A/52A (AC-3)"),
		new Codec("adpcm_4xm",        "ADPCM 4X Movie"),
		new Codec("adpcm_adx",        "SEGA CRI ADX ADPCM"),
		new Codec("adpcm_ct",         "ADPCM Creative Technology"),
		new Codec("adpcm_ea",         "ADPCM Electronic Arts"),
		new Codec("adpcm_ea_maxis_xa",  "ADPCM Electronic Arts Maxis CDROM XA"),
		new Codec("adpcm_ea_r1",      "ADPCM Electronic Arts R1"),
		new Codec("adpcm_ea_r2",      "ADPCM Electronic Arts R2"),
		new Codec("adpcm_ea_r3",      "ADPCM Electronic Arts R3"),
		new Codec("adpcm_ea_xas",     "ADPCM Electronic Arts XAS"),
		new Codec("adpcm_ima_amv",    "ADPCM IMA AMV"),
		new Codec("adpcm_ima_apc",    "ADPCM IMA CRYO APC"),
		new Codec("adpcm_ima_dk3",    "ADPCM IMA Duck DK3"),
		new Codec("adpcm_ima_dk4",    "ADPCM IMA Duck DK4"),
		new Codec("adpcm_ima_ea_eacs",  "ADPCM IMA Electronic Arts EACS"),
		new Codec("adpcm_ima_ea_sead",  "ADPCM IMA Electronic Arts SEAD"),
		new Codec("adpcm_ima_iss",    "ADPCM IMA Funcom ISS"),
		new Codec("adpcm_ima_qt",     "ADPCM IMA QuickTime"),
		new Codec("adpcm_ima_smjpeg",  "ADPCM IMA Loki SDL MJPEG"),
		new Codec("adpcm_ima_wav",    "ADPCM IMA WAV"),
		new Codec("adpcm_ima_ws",     "ADPCM IMA Westwood"),
		new Codec("adpcm_ms",         "ADPCM Microsoft"),
		new Codec("adpcm_sbpro_2",    "ADPCM Sound Blaster Pro 2-bit"),
		new Codec("adpcm_sbpro_3",    "ADPCM Sound Blaster Pro 2.6-bit"),
		new Codec("adpcm_sbpro_4",    "ADPCM Sound Blaster Pro 4-bit"),
		new Codec("adpcm_swf",        "ADPCM Shockwave Flash"),
		new Codec("adpcm_thp",        "ADPCM Nintendo Gamecube THP"),
		new Codec("adpcm_xa",         "ADPCM CDROM XA"),
		new Codec("adpcm_yamaha",     "ADPCM Yamaha"),
		new Codec("alac",             "ALAC (Apple Lossless Audio Codec)"),
		new Codec("als",              "MPEG-4 Audio Lossless Coding (ALS)"),
		new Codec("amrnb",            "Adaptive Multi-Rate NarrowBand"),
		new Codec("amrwb",            "Adaptive Multi-Rate WideBand"),
		new Codec("amv",              "AMV Video"),
		new Codec("anm",              "Deluxe Paint Animation"),
		new Codec("ansi",             "ASCII/ANSI art"),
		new Codec("ape",              "Monkey's Audio"),
		new Codec("ass",              "Advanced SubStation Alpha subtitle"),
		new Codec("asv1",             "ASUS V1"),
		new Codec("asv2",             "ASUS V2"),
		new Codec("atrac1",           "Atrac 1 (Adaptive TRansform Acoustic Coding)"),
		new Codec("atrac3",           "Atrac 3 (Adaptive TRansform Acoustic Coding 3)"),
		new Codec("aura",             "Auravision AURA"),
		new Codec("aura2",            "Auravision Aura 2"),
		new Codec("avrp",             "Avid 1:1 10-bit RGB Packer"),
		new Codec("avs",              "AVS (Audio Video Standard) video"),
		new Codec("bethsoftvid",      "Bethesda VID video"),
		new Codec("bfi",              "Brute Force & Ignorance"),
		new Codec("binkaudio_dct",    "Bink Audio (DCT)"),
		new Codec("binkaudio_rdft",   "Bink Audio (RDFT)"),
		new Codec("binkvideo",        "Bink video"),
		new Codec("bintext",          "Binary text"),
		new Codec("bmp",              "BMP image"),
		new Codec("bmv_audio",        "Discworld II BMV audio"),
		new Codec("bmv_video",        "Discworld II BMV video"),
		new Codec("c93",              "Interplay C93"),
		new Codec("camstudio",        "CamStudio"),
		new Codec("camtasia",         "TechSmith Screen Capture Codec"),
		new Codec("cavs",             "Chinese AVS video (AVS1-P2, JiZhun profile)"),
		new Codec("cdgraphics",       "CD Graphics video"),
		new Codec("cinepak",          "Cinepak"),
		new Codec("cljr",             "Cirrus Logic AccuPak"),
		new Codec("cook",             "COOK"),
		new Codec("cyuv",             "Creative YUV (CYUV)"),
		new Codec("dca",              "DCA (DTS Coherent Acoustics)"),
		new Codec("dfa",              "Chronomaster DFA"),
		new Codec("dirac",            "BBC Dirac VC-2"),
		new Codec("dnxhd",            "VC3/DNxHD"),
		new Codec("dpx",              "DPX image"),
		new Codec("dsicinaudio",      "Delphine Software International CIN audio"),
		new Codec("dsicinvideo",      "Delphine Software International CIN video"),
		new Codec("dvbsub",           "DVB subtitles"),
		new Codec("dvdsub",           "DVD subtitles"),
		new Codec("dvvideo",          "DV (Digital Video)"),
		new Codec("dxa",              "Feeble Files/ScummVM DXA"),
		new Codec("dxtory",           "Dxtory"),
		new Codec("eac3",             "ATSC A/52 E-AC-3"),
		new Codec("eacmv",            "Electronic Arts CMV video"),
		new Codec("eamad",            "Electronic Arts Madcow Video"),
		new Codec("eatgq",            "Electronic Arts TGQ video"),
		new Codec("eatgv",            "Electronic Arts TGV video"),
		new Codec("eatqi",            "Electronic Arts TQI Video"),
		new Codec("escape124",        "Escape 124"),
		new Codec("escape130",        "Escape 130"),
		new Codec("ffv1",             "FFmpeg video codec #1"),
		new Codec("ffvhuff",          "Huffyuv FFmpeg variant"),
		new Codec("flac",             "FLAC (Free Lossless Audio Codec)"),
		new Codec("flashsv",          "Flash Screen Video"),
		new Codec("flashsv2",         "Flash Screen Video Version 2"),
		new Codec("flic",             "Autodesk Animator Flic video"),
		new Codec("flv",              "Flash Video (FLV) / Sorenson Spark / Sorenson H.263"),
		new Codec("fraps",            "Fraps"),
		new Codec("frwu",             "Forward Uncompressed"),
		new Codec("g722",             "G.722 ADPCM"),
		new Codec("g723_1",           "G.723.1"),
		new Codec("g726",             "G.726 ADPCM"),
		new Codec("g729",             "G.729"),
		new Codec("gif",              "GIF (Graphics Interchange Format)"),
		new Codec("gsm",              "GSM"),
		new Codec("gsm_ms",           "GSM Microsoft variant"),
		new Codec("h261",             "H.261"),
		new Codec("h263",             "H.263 / H.263-1996"),
		new Codec("h263i",            "Intel H.263"),
		new Codec("h263p",            "H.263+ / H.263-1998 / H.263 version 2"),
		new Codec("h264",             "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10"),
		new Codec("h264_vdpau",       "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (VDPAU acceleration)"),
		new Codec("huffyuv",          "Huffyuv / HuffYUV"),
		new Codec("idcinvideo",       "id Quake II CIN video"),
		new Codec("idf",              "iCEDraw text"),
		new Codec("iff_byterun1",     "IFF ByteRun1"),
		new Codec("iff_ilbm",         "IFF ILBM"),
		new Codec("imc",              "IMC (Intel Music Coder)"),
		new Codec("indeo2",           "Intel Indeo 2"),
		new Codec("indeo3",           "Intel Indeo 3"),
		new Codec("indeo4",           "Intel Indeo Video Interactive 4"),
		new Codec("indeo5",           "Intel Indeo Video Interactive 5"),
		new Codec("interplay_dpcm",   "DPCM Interplay"),
		new Codec("interplayvideo",   "Interplay MVE video"),
		new Codec("j2k",              "JPEG 2000"),
		new Codec("jpegls",           "JPEG-LS"),
		new Codec("jv",               "Bitmap Brothers JV video"),
		new Codec("kgv1",             "Kega Game Video"),
		new Codec("kmvc",             "Karl Morton's video codec"),
		new Codec("lagarith",         "Lagarith lossless"),
		new Codec("libgsm",           "libgsm GSM"),
		new Codec("libgsm_ms",        "libgsm GSM Microsoft variant"),
		new Codec("libmp3lame",       "libmp3lame MP3 (MPEG audio layer 3)"),
		new Codec("libopenjpeg",      "OpenJPEG based JPEG 2000 encoder"),
		new Codec("libschroedinger",  "libschroedinger Dirac 2.2"),
		new Codec("libspeex",         "libspeex Speex"),
		new Codec("libtheora",        "libtheora Theora"),
		new Codec("libvorbis",        "libvorbis Vorbis"),
		new Codec("libvpx",           "libvpx VP8"),
		new Codec("libx264",          "libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10"),
		new Codec("libx264rgb",       "libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 RGB"),
		new Codec("ljpeg",            "Lossless JPEG"),
		new Codec("loco",             "LOCO"),
		new Codec("mace3",            "MACE (Macintosh Audio Compression/Expansion) 3:1"),
		new Codec("mace6",            "MACE (Macintosh Audio Compression/Expansion) 6:1"),
		new Codec("mdec",             "Sony PlayStation MDEC (Motion DECoder)"),
		new Codec("mimic",            "Mimic"),
		new Codec("mjpeg",            "MJPEG (Motion JPEG)"),
		new Codec("mjpegb",           "Apple MJPEG-B"),
		new Codec("mlp",              "MLP (Meridian Lossless Packing)"),
		new Codec("mmvideo",          "American Laser Games MM Video"),
		new Codec("motionpixels",     "Motion Pixels video"),
		new Codec("mp1",              "MP1 (MPEG audio layer 1)"),
		new Codec("mp1float",         "MP1 (MPEG audio layer 1)"),
		new Codec("mp2",              "MP2 (MPEG audio layer 2)"),
		new Codec("mp2float",         "MP2 (MPEG audio layer 2)"),
		new Codec("mp3",              "MP3 (MPEG audio layer 3)"),
		new Codec("mp3adu",           "ADU (Application Data Unit) MP3 (MPEG audio layer 3)"),
		new Codec("mp3adufloat",      "ADU (Application Data Unit) MP3 (MPEG audio layer 3)"),
		new Codec("mp3float",         "MP3 (MPEG audio layer 3)"),
		new Codec("mp3on4",           "MP3onMP4"),
		new Codec("mp3on4float",      "MP3onMP4"),
		new Codec("mpc7",             "Musepack SV7"),
		new Codec("mpc8",             "Musepack SV8"),
		new Codec("mpeg1video",       "MPEG-1 video"),
		new Codec("mpeg1video_vdpau",  "MPEG-1 video (VDPAU acceleration)"),
		new Codec("mpeg2video",       "MPEG-2 video"),
		new Codec("mpeg4",            "MPEG-4 part 2"),
		new Codec("mpeg4_vdpau",      "MPEG-4 part 2 (VDPAU)"),
		new Codec("mpegvideo",        "MPEG-1 video"),
		new Codec("mpegvideo_vdpau",  "MPEG-1/2 video (VDPAU acceleration)"),
		new Codec("mpegvideo_xvmc",   "MPEG-1/2 video XvMC (X-Video Motion Compensation)"),
		new Codec("msmpeg4",          "MPEG-4 part 2 Microsoft variant version 3"),
		new Codec("msmpeg4v1",        "MPEG-4 part 2 Microsoft variant version 1"),
		new Codec("msmpeg4v2",        "MPEG-4 part 2 Microsoft variant version 2"),
		new Codec("msrle",            "Microsoft RLE"),
		new Codec("msvideo1",         "Microsoft Video-1"),
		new Codec("mszh",             "LCL (LossLess Codec Library) MSZH"),
		new Codec("mxpeg",            "Mobotix MxPEG video"),
		new Codec("nellymoser",       "Nellymoser Asao"),
		new Codec("nuv",              "NuppelVideo/RTJPEG"),
		new Codec("pam",              "PAM (Portable AnyMap) image"),
		new Codec("pbm",              "PBM (Portable BitMap) image"),
		new Codec("pcm_alaw",         "PCM A-law"),
		new Codec("pcm_bluray",       "PCM signed 16|20|24-bit big-endian for Blu-ray media"),
		new Codec("pcm_dvd",          "PCM signed 20|24-bit big-endian"),
		new Codec("pcm_f32be",        "PCM 32-bit floating point big-endian"),
		new Codec("pcm_f32le",        "PCM 32-bit floating point little-endian"),
		new Codec("pcm_f64be",        "PCM 64-bit floating point big-endian"),
		new Codec("pcm_f64le",        "PCM 64-bit floating point little-endian"),
		new Codec("pcm_lxf",          "PCM signed 20-bit little-endian planar"),
		new Codec("pcm_mulaw",        "PCM mu-law"),
		new Codec("pcm_s16be",        "PCM signed 16-bit big-endian"),
		new Codec("pcm_s16le",        "PCM signed 16-bit little-endian"),
		new Codec("pcm_s16le_planar",  "PCM 16-bit little-endian planar"),
		new Codec("pcm_s24be",        "PCM signed 24-bit big-endian"),
		new Codec("pcm_s24daud",      "PCM D-Cinema audio signed 24-bit"),
		new Codec("pcm_s24le",        "PCM signed 24-bit little-endian"),
		new Codec("pcm_s32be",        "PCM signed 32-bit big-endian"),
		new Codec("pcm_s32le",        "PCM signed 32-bit little-endian"),
		new Codec("pcm_s8",           "PCM signed 8-bit"),
		new Codec("pcm_s8_planar",    "PCM signed 8-bit planar"),
		new Codec("pcm_u16be",        "PCM unsigned 16-bit big-endian"),
		new Codec("pcm_u16le",        "PCM unsigned 16-bit little-endian"),
		new Codec("pcm_u24be",        "PCM unsigned 24-bit big-endian"),
		new Codec("pcm_u24le",        "PCM unsigned 24-bit little-endian"),
		new Codec("pcm_u32be",        "PCM unsigned 32-bit big-endian"),
		new Codec("pcm_u32le",        "PCM unsigned 32-bit little-endian"),
		new Codec("pcm_u8",           "PCM unsigned 8-bit"),
		new Codec("pcm_zork",         "PCM Zork"),
		new Codec("pcx",              "PC Paintbrush PCX image"),
		new Codec("pgm",              "PGM (Portable GrayMap) image"),
		new Codec("pgmyuv",           "PGMYUV (Portable GrayMap YUV) image"),
		new Codec("pgssub",           "HDMV Presentation Graphic Stream subtitles"),
		new Codec("pictor",           "Pictor/PC Paint"),
		new Codec("png",              "PNG image"),
		new Codec("ppm",              "PPM (Portable PixelMap) image"),
		new Codec("prores",           "Apple ProRes"),
		new Codec("prores_lgpl",      "Apple ProRes (iCodec Pro)"),
		new Codec("ptx",              "V.Flash PTX image"),
		new Codec("qcelp",            "QCELP / PureVoice"),
		new Codec("qdm2",             "QDesign Music Codec 2"),
		new Codec("qdraw",            "Apple QuickDraw"),
		new Codec("qpeg",             "Q-team QPEG"),
		new Codec("qtrle",            "QuickTime Animation (RLE) video"),
		new Codec("r10k",             "AJA Kona 10-bit RGB Codec"),
		new Codec("r210",             "Uncompressed RGB 10-bit"),
		new Codec("rawvideo",         "raw video"),
		new Codec("real_144",         "RealAudio 1.0 (14.4K) encoder"),
		new Codec("real_288",         "RealAudio 2.0 (28.8K)"),
		new Codec("rl2",              "RL2 video"),
		new Codec("roq_dpcm",         "id RoQ DPCM"),
		new Codec("roqvideo",         "id RoQ video"),
		new Codec("rpza",             "QuickTime video (RPZA)"),
		new Codec("rv10",             "RealVideo 1.0"),
		new Codec("rv20",             "RealVideo 2.0"),
		new Codec("rv30",             "RealVideo 3.0"),
		new Codec("rv40",             "RealVideo 4.0"),
		new Codec("s302m",            "SMPTE 302M"),
		new Codec("sgi",              "SGI image"),
		new Codec("shorten",          "Shorten"),
		new Codec("sipr",             "RealAudio SIPR / ACELP.NET"),
		new Codec("smackaud",         "Smacker audio"),
		new Codec("smackvid",         "Smacker video"),
		new Codec("smc",              "QuickTime Graphics (SMC)"),
		new Codec("snow",             "Snow"),
		new Codec("sol_dpcm",         "DPCM Sol"),
		new Codec("sonic",            "Sonic"),
		new Codec("sonicls",          "Sonic lossless"),
		new Codec("sp5x",             "Sunplus JPEG (SP5X)"),
		new Codec("srt",              "SubRip subtitle"),
		new Codec("sunrast",          "Sun Rasterfile image"),
		new Codec("svq1",             "Sorenson Vector Quantizer 1 / Sorenson Video 1 / SVQ1"),
		new Codec("svq3",             "Sorenson Vector Quantizer 3 / Sorenson Video 3 / SVQ3"),
		new Codec("targa",            "Truevision Targa image"),
		new Codec("theora",           "Theora"),
		new Codec("thp",              "Nintendo Gamecube THP video"),
		new Codec("tiertexseqvideo",  "Tiertex Limited SEQ video"),
		new Codec("tiff",             "TIFF image"),
		new Codec("tmv",              "8088flex TMV"),
		new Codec("truehd",           "TrueHD"),
		new Codec("truemotion1",      "Duck TrueMotion 1.0"),
		new Codec("truemotion2",      "Duck TrueMotion 2.0"),
		new Codec("truespeech",       "DSP Group TrueSpeech"),
		new Codec("tta",              "True Audio (TTA)"),
		new Codec("twinvq",           "VQF TwinVQ"),
		new Codec("txd",              "Renderware TXD (TeXture Dictionary) image"),
		new Codec("ultimotion",       "IBM UltiMotion"),
		new Codec("utvideo",          "Ut Video"),
		new Codec("v210",             "Uncompressed 4:2:2 10-bit"),
		new Codec("v210x",            "Uncompressed 4:2:2 10-bit"),
		new Codec("v308",             "Uncompressed packed 4:4:4"),
		new Codec("v410",             "Uncompressed 4:4:4 10-bit"),
		new Codec("vb",               "Beam Software VB"),
		new Codec("vble",             "VBLE Lossless Codec"),
		new Codec("vc1",              "SMPTE VC-1"),
		new Codec("vc1_vdpau",        "SMPTE VC-1 VDPAU"),
		new Codec("vc1image",         "Windows Media Video 9 Image v2"),
		new Codec("vcr1",             "ATI VCR1"),
		new Codec("vmdaudio",         "Sierra VMD audio"),
		new Codec("vmdvideo",         "Sierra VMD video"),
		new Codec("vmnc",             "VMware Screen Codec / VMware Video"),
		new Codec("vorbis",           "Vorbis"),
		new Codec("vp3",              "On2 VP3"),
		new Codec("vp5",              "On2 VP5"),
		new Codec("vp6",              "On2 VP6"),
		new Codec("vp6a",             "On2 VP6 (Flash version, with alpha channel)"),
		new Codec("vp6f",             "On2 VP6 (Flash version)"),
		new Codec("vp8",              "On2 VP8"),
		new Codec("vqavideo",         "Westwood Studios VQA (Vector Quantized Animation) video"),
		new Codec("wavesynth",        "Wave synthesis pseudo-codec"),
		new Codec("wavpack",          "WavPack"),
		new Codec("wmalossless",      "Windows Media Audio 9 Lossless"),
		new Codec("wmapro",           "Windows Media Audio 9 Professional"),
		new Codec("wmav1",            "Windows Media Audio 1"),
		new Codec("wmav2",            "Windows Media Audio 2"),
		new Codec("wmavoice",         "Windows Media Audio Voice"),
		new Codec("wmv1",             "Windows Media Video 7"),
		new Codec("wmv2",             "Windows Media Video 8"),
		new Codec("wmv3",             "Windows Media Video 9"),
		new Codec("wmv3_vdpau",       "Windows Media Video 9 VDPAU"),
		new Codec("wmv3image",        "Windows Media Video 9 Image"),
		new Codec("wnv1",             "Winnov WNV1"),
		new Codec("ws_snd1",          "Westwood Audio (SND1)"),
		new Codec("xan_dpcm",         "DPCM Xan"),
		new Codec("xan_wc3",          "Wing Commander III / Xan"),
		new Codec("xan_wc4",          "Wing Commander IV / Xxan"),
		new Codec("xbin",             "eXtended BINary text"),
		new Codec("xl",               "Miro VideoXL"),
		new Codec("xsub",             "DivX subtitles (XSUB)"),
		new Codec("xwd",              "XWD (X Window Dump) image"),
		new Codec("y41p",             "Uncompressed YUV 4:1:1 12-bit"),
		new Codec("yop",              "Psygnosis YOP Video"),
		new Codec("yuv4",             "Uncompressed packed 4:2:0"),
		new Codec("zlib",             "LCL (LossLess Codec Library) ZLIB"),
		new Codec("zmbv",             "Zip Motion Blocks Video")
	};
}
