package net.bramp.ffmpeg;

import net.bramp.ffmpeg.info.Format;

/**
 * Class that contains all Formats as defined in the unit tests
 * This should not be used to test if a format is available, because every
 * install of ffmpeg is different. Call ffmpeg.formats() to discover.
 * 
 * @author bramp
 *
 */
public class Formats {

	public static Format[] FORMATS = new Format[] {
		new Format("3g2",            "3GP2 format"), 
		new Format("3gp",            "3GP format"), 
		new Format("4xm",            "4X Technologies format"), 
		new Format("IFF",            "IFF format"), 
		new Format("ISS",            "Funcom ISS format"), 
		new Format("MTV",            "MTV format"), 
		new Format("RoQ",            "raw id RoQ format"), 
		new Format("a64",            "a64 - video for Commodore 64"), 
		new Format("aac",            "raw ADTS AAC"), 
		new Format("ac3",            "raw AC-3"), 
		new Format("act",            "ACT Voice file format"), 
		new Format("adf",            "Artworx Data Format"), 
		new Format("adts",           "ADTS AAC"), 
		new Format("adx",            "CRI ADX"), 
		new Format("aea",            "MD STUDIO audio"), 
		new Format("aiff",           "Audio IFF"), 
		new Format("alaw",           "PCM A-law format"), 
		new Format("alsa",           "ALSA audio output"), 
		new Format("amr",            "3GPP AMR file format"), 
		new Format("anm",            "Deluxe Paint Animation"), 
		new Format("apc",            "CRYO APC format"), 
		new Format("ape",            "Monkey's Audio"), 
		new Format("applehttp",      "Apple HTTP Live Streaming format"), 
		new Format("asf",            "ASF format"), 
		new Format("asf_stream",     "ASF format"), 
		new Format("ass",            "Advanced SubStation Alpha subtitle format"), 
		new Format("au",             "SUN AU format"), 
		new Format("avi",            "AVI format"), 
		new Format("avm2",           "Flash 9 (AVM2) format"), 
		new Format("avs",            "AVS format"), 
		new Format("bethsoftvid",    "Bethesda Softworks VID format"), 
		new Format("bfi",            "Brute Force & Ignorance"), 
		new Format("bin",            "Binary text"), 
		new Format("bink",           "Bink"), 
		new Format("bit",            "G.729 BIT file format"), 
		new Format("bmv",            "Discworld II BMV"), 
		new Format("c93",            "Interplay C93"), 
		new Format("caf",            "Apple Core Audio Format"), 
		new Format("cavsvideo",      "raw Chinese AVS video"), 
		new Format("cdg",            "CD Graphics Format"), 
		new Format("crc",            "CRC testing format"), 
		new Format("daud",           "D-Cinema audio format"), 
		new Format("dfa",            "Chronomaster DFA"), 
		new Format("dirac",          "raw Dirac"), 
		new Format("dnxhd",          "raw DNxHD (SMPTE VC-3)"), 
		new Format("dsicin",         "Delphine Software International CIN format"), 
		new Format("dts",            "raw DTS"), 
		new Format("dv",             "DV video format"), 
		new Format("dv1394",         "DV1394 A/V grab"), 
		new Format("dvd",            "MPEG-2 PS format (DVD VOB)"), 
		new Format("dxa",            "DXA"), 
		new Format("ea",             "Electronic Arts Multimedia Format"), 
		new Format("ea_cdata",       "Electronic Arts cdata"), 
		new Format("eac3",           "raw E-AC-3"), 
		new Format("f32be",          "PCM 32 bit floating-point big-endian format"), 
		new Format("f32le",          "PCM 32 bit floating-point little-endian format"), 
		new Format("f64be",          "PCM 64 bit floating-point big-endian format"), 
		new Format("f64le",          "PCM 64 bit floating-point little-endian format"), 
		new Format("fbdev",          "Linux framebuffer"), 
		new Format("ffm",            "FFM (FFserver live feed) format"), 
		new Format("ffmetadata",     "FFmpeg metadata in text format"), 
		new Format("film_cpk",       "Sega FILM/CPK format"), 
		new Format("filmstrip",      "Adobe Filmstrip"), 
		new Format("flac",           "raw FLAC"), 
		new Format("flic",           "FLI/FLC/FLX animation format"), 
		new Format("flv",            "FLV format"), 
		new Format("framecrc",       "framecrc testing format"), 
		new Format("framemd5",       "Per-frame MD5 testing format"), 
		new Format("g722",           "raw G.722"), 
		new Format("g723_1",         "raw G.723.1"), 
		new Format("g729",           "G.729 raw format demuxer"), 
		new Format("gif",            "GIF Animation"), 
		new Format("gsm",            "raw GSM"), 
		new Format("gxf",            "GXF format"), 
		new Format("h261",           "raw H.261"), 
		new Format("h263",           "raw H.263"), 
		new Format("h264",           "raw H.264 video format"), 
		new Format("ico",            "Microsoft Windows ICO"), 
		new Format("idcin",          "id Cinematic format"), 
		new Format("idf",            "iCE Draw File"), 
		new Format("image2",         "image2 sequence"), 
		new Format("image2pipe",     "piped image2 sequence"), 
		new Format("ingenient",      "raw Ingenient MJPEG"), 
		new Format("ipmovie",        "Interplay MVE format"), 
		new Format("ipod",           "iPod H.264 MP4 format"), 
		new Format("ismv",           "ISMV/ISMA (Smooth Streaming) format"), 
		new Format("iv8",            "A format generated by IndigoVision 8000 video server"), 
		new Format("ivf",            "On2 IVF"), 
		new Format("jack",           "JACK Audio Connection Kit"), 
		new Format("jv",             "Bitmap Brothers JV"), 
		new Format("latm",           "LOAS/LATM"), 
		new Format("lavfi",          "Libavfilter virtual input device"), 
		new Format("libcdio",        ""), 
		new Format("libdc1394",      "dc1394 A/V grab"), 
		new Format("lmlm4",          "lmlm4 raw format"), 
		new Format("loas",           "LOAS AudioSyncStream"), 
		new Format("lxf",            "VR native stream format (LXF)"), 
		new Format("m4v",            "raw MPEG-4 video format"), 
		new Format("matroska",       "Matroska file format"), 
		new Format("matroska,webm",  "Matroska/WebM file format"), 
		new Format("md5",            "MD5 testing format"), 
		new Format("microdvd",       "MicroDVD subtitle format"), 
		new Format("mjpeg",          "raw MJPEG video"), 
		new Format("mkvtimestamp_v2","extract pts as timecode v2 format, as defined by mkvtoolnix"), 
		new Format("mlp",            "raw MLP"), 
		new Format("mm",             "American Laser Games MM format"), 
		new Format("mmf",            "Yamaha SMAF"), 
		new Format("mov",            "MOV format"), 
		new Format("mov,mp4,m4a,3gp,3g2,mj2", "QuickTime/MPEG-4/Motion JPEG 2000 format"), 
		new Format("mp2",            "MPEG audio layer 2"), 
		new Format("mp3",            "MPEG audio layer 3"), 
		new Format("mp4",            "MP4 format"), 
		new Format("mpc",            "Musepack"), 
		new Format("mpc8",           "Musepack SV8"), 
		new Format("mpeg",           "MPEG-1 System format"), 
		new Format("mpeg1video",     "raw MPEG-1 video"), 
		new Format("mpeg2video",     "raw MPEG-2 video"), 
		new Format("mpegts",         "MPEG-2 transport stream format"), 
		new Format("mpegtsraw",      "MPEG-2 raw transport stream format"), 
		new Format("mpegvideo",      "raw MPEG video"), 
		new Format("mpjpeg",         "MIME multipart JPEG format"), 
		new Format("msnwctcp",       "MSN TCP Webcam stream"), 
		new Format("mulaw",          "PCM mu-law format"), 
		new Format("mvi",            "Motion Pixels MVI format"), 
		new Format("mxf",            "Material eXchange Format"), 
		new Format("mxf_d10",        "Material eXchange Format, D-10 Mapping"), 
		new Format("mxg",            "MxPEG clip file format"), 
		new Format("nc",             "NC camera feed format"), 
		new Format("nsv",            "Nullsoft Streaming Video"), 
		new Format("null",           "raw null video format"), 
		new Format("nut",            "NUT format"), 
		new Format("nuv",            "NuppelVideo format"), 
		new Format("ogg",            "Ogg"), 
		new Format("oma",            "Sony OpenMG audio"), 
		new Format("oss",            "Open Sound System playback"), 
		new Format("pmp",            "Playstation Portable PMP format"), 
		new Format("psp",            "PSP MP4 format"), 
		new Format("psxstr",         "Sony Playstation STR format"), 
		new Format("pulse",          "Pulse audio input"), 
		new Format("pva",            "TechnoTrend PVA file and stream format"), 
		new Format("qcp",            "QCP format"), 
		new Format("r3d",            "REDCODE R3D format"), 
		new Format("rawvideo",       "raw video format"), 
		new Format("rcv",            "VC-1 test bitstream"), 
		new Format("rl2",            "RL2 format"), 
		new Format("rm",             "RealMedia format"), 
		new Format("rpl",            "RPL/ARMovie format"), 
		new Format("rso",            "Lego Mindstorms RSO format"), 
		new Format("rtp",            "RTP output format"), 
		new Format("rtsp",           "RTSP output format"), 
		new Format("s16be",          "PCM signed 16 bit big-endian format"), 
		new Format("s16le",          "PCM signed 16 bit little-endian format"), 
		new Format("s24be",          "PCM signed 24 bit big-endian format"), 
		new Format("s24le",          "PCM signed 24 bit little-endian format"), 
		new Format("s32be",          "PCM signed 32 bit big-endian format"), 
		new Format("s32le",          "PCM signed 32 bit little-endian format"), 
		new Format("s8",             "PCM signed 8 bit format"), 
		new Format("sap",            "SAP output format"), 
		new Format("sbg",            "SBaGen binaural beats script"), 
		new Format("sdl",            "SDL output device"), 
		new Format("sdp",            "SDP"), 
		new Format("segment",        "segment muxer"), 
		new Format("shn",            "raw Shorten"), 
		new Format("siff",           "Beam Software SIFF"), 
		new Format("smjpeg",         "Loki SDL MJPEG"), 
		new Format("smk",            "Smacker video"), 
		new Format("sol",            "Sierra SOL format"), 
		new Format("sox",            "SoX native format"), 
		new Format("spdif",          "IEC 61937 (used on S/PDIF - IEC958)"), 
		new Format("srt",            "SubRip subtitle format"), 
		new Format("svcd",           "MPEG-2 PS format (VOB)"), 
		new Format("swf",            "Flash format"), 
		new Format("thp",            "THP"), 
		new Format("tiertexseq",     "Tiertex Limited SEQ format"), 
		new Format("tmv",            "8088flex TMV"), 
		new Format("truehd",         "raw TrueHD"), 
		new Format("tta",            "True Audio"), 
		new Format("tty",            "Tele-typewriter"), 
		new Format("txd",            "Renderware TeXture Dictionary"), 
		new Format("u16be",          "PCM unsigned 16 bit big-endian format"), 
		new Format("u16le",          "PCM unsigned 16 bit little-endian format"), 
		new Format("u24be",          "PCM unsigned 24 bit big-endian format"), 
		new Format("u24le",          "PCM unsigned 24 bit little-endian format"), 
		new Format("u32be",          "PCM unsigned 32 bit big-endian format"), 
		new Format("u32le",          "PCM unsigned 32 bit little-endian format"), 
		new Format("u8",             "PCM unsigned 8 bit format"), 
		new Format("vc1",            "raw VC-1"), 
		new Format("vc1test",        "VC-1 test bitstream format"), 
		new Format("vcd",            "MPEG-1 System format (VCD)"), 
		new Format("video4linux2,v4l2", "Video4Linux2 device grab"), 
		new Format("vmd",            "Sierra VMD format"), 
		new Format("vob",            "MPEG-2 PS format (VOB)"), 
		new Format("voc",            "Creative Voice file format"), 
		new Format("vqf",            "Nippon Telegraph and Telephone Corporation (NTT) TwinVQ"), 
		new Format("w64",            "Sony Wave64 format"), 
		new Format("wav",            "WAV format"), 
		new Format("wc3movie",       "Wing Commander III movie format"), 
		new Format("webm",           "WebM file format"), 
		new Format("wsaud",          "Westwood Studios audio format"), 
		new Format("wsvqa",          "Westwood Studios VQA format"), 
		new Format("wtv",            "Windows Television (WTV)"), 
		new Format("wv",             "WavPack"), 
		new Format("x11grab",        "X11grab"), 
		new Format("xa",             "Maxis XA File Format"), 
		new Format("xbin",           "eXtended BINary text (XBIN)"), 
		new Format("xmv",            "Microsoft XMV"), 
		new Format("xwma",           "Microsoft xWMA"), 
		new Format("yop",            "Psygnosis YOP Format"), 
		new Format("yuv4mpegpipe",   "YUV4MPEG pipe format")
	};
}
