name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [11, 17, 21]

    name: JDK ${{ matrix.java-version }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn --batch-mode verify -Dgpg.skip

      - name: Update dependency graph
        if: matrix.java-version == '21' && github.event_name == 'push'
        uses: advanced-security/maven-dependency-submission-action@v5
        continue-on-error: true
